### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by CrackHub** [7rebux/league-tools#18]
If folder name has **"#"** character app not work, it shows white screen.

**Comment by 7rebux** [comment]
Which folder are you refering to?

**Comment by CrackHub** [comment]
"D:\Riot Games\#league-tools\league-tools.exe"

**Comment by 7rebux** [comment]
> `"D:\Riot Games\#league-tools\league-tools.exe"`

Generally I would avoid `#` in file system paths, especially in web app related things. What's happening here is that the `#` is treated as an linked [HTML anchor](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a). So everything after the `#`  is gonna be treated as an anchor name rather than the actual path. Seems to be a more or less "bug" of electron apps in general.
